### ISSUE TITLE
Is there a way for me to stop receiving messages from this DM Bot?

### ISSUE THREAD

**Issue by EnergixCoding** [Lemons1337/Discord-DM-Bot#12]
So, there has been someone advertising a minecraft server called llamacraft.fun and I was wondering how I could stop being dm botted as its annoying af.

**Comment by PaimonWheeWhee** [comment]
Turn your DMs off or just leave the server the bots are DMing you from. And how do you know that they're using this specific service?

**Comment by EnergixCoding** [comment]
just seems like it

**Comment by AntiGamerPlayzz** [comment]
imagine closing ur own issue
